import Head from 'next/head'

import { useState } from 'react'



export default function Scan() {

  const [iResolution, iSetResolution] = useState(2)
  const [resolution, setResolution] = useState([75,100,200,300,600,1200] as Array<Number>)
  function handleResolution(event:any) {
    iSetResolution(event.target.value)
  }

  const [iColor, iSetColor] = useState(2)
  const [color, setColor] = useState(['Lineart', 'Gray', 'Color'] as Array<String>)
  function handleColor(event:any) {
    iSetColor(event.target.value)
  }

  const [brightness, setBrightness] = useState(1000)
  function handleBrightness(event:any) {
    setBrightness(event.target.value)
  }
  const [contrast, setContrast] = useState(1000)
  function handleContrast(event:any) {
    setContrast(event.target.value)
  }
  const path=`/home/USER/Pictures/Scans/${Date.now()}.png`
  var jsonData = {
    "--mode": color[iColor],
    "--resolution": resolution[iResolution],
    "--contrast": contrast,
    "--brightness": brightness,
    ">":path
  }

  function sendPost() {
    
    // Send data to the backend via POST
    fetch('/api/hello', {  // Enter your IP address here

      method: 'POST', 
      mode: 'cors', 
      body: JSON.stringify(jsonData) // body data type must match "Content-Type" header

    })
    
  }

  return (
    <div>
        
      <Head>
        <title>GUI SCAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
<div className=" justify-center text-center align-center">

<div>
  <h1>Modo</h1>
  <input type="range"  value={`${iColor}`} min="0" max="2" onChange={iColor => handleColor(iColor)} />
  <label>{`${color[iColor]}`}</label>
  </div>
<div>
  <h1>Resolucion</h1>
<input type="range" value={`${iResolution}`} min="0" max="5" onChange={iResolution => handleResolution(iResolution)} />
  <label>{`${resolution[iResolution]}`}</label>
</div>
  <div>
    <h1>Brillo</h1>
  <input type="range"  min="0" max="2000"  value={`${brightness}`} onChange={e => handleBrightness(e)} />
  <label>{brightness}</label>
  </div>
  <div>
  <h1>Contraste</h1>
  <input type="range" min="0" max="2000"  value={`${contrast}`} onChange={e => handleContrast(e)} />
  <label>{contrast}</label>
  </div>

  <button onClick={sendPost} type="submit" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>



</div>    
          
       
 
    </div>
  );
}